### ISSUE TITLE
epic - too complicated teaiso does the same in any linux with no depens

### ISSUE THREAD

**Issue by mckaygerhard** [Ryan1729/foxbook-setup#1]
immediate disaproved: reasons

1️⃣ too complicated setup to produce so simplistic thing
2️⃣ rust shit
3️⃣ venenuxmkiso or tearlinux teaiso does the same with only bash and tools

https://codeberg.org/alpine/alpine-isomaker check that .. doe snot need special setups and it works in any linux.. not only few ones and doe snot need setup a rusnt env :vomiting_face:

**Comment by Ryan1729** [comment]
Yes, there’s probably simpler ways to achieve the same thing, for given definitions of simpler. 

Anyone who doesn’t like it can have a full $0 refund.
